# Generated by Django 6.0 on 2025-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час доступу')),
                ('status', models.IntegerField(verbose_name='Статус відповіді сервера')),
            ],
        ),
    ]
